---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - fiveg.kt.com
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fiveg.kt.com
  resources:
  - backups/finalizers
  verbs:
  - update
- apiGroups:
  - fiveg.kt.com
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
